{
  all         = false; # appdev
  angular     = false; # appdev webdev
  ansible     = false; # appdev webdev
  arduino     = false; # apple
  assembly    = false; # apple
  astro       = false; # beam
  awk         = false; # beam
  bash        = false; # beam
  c           = false; # configs
  clojure     = false; # configs devops
  cpp         = false; # configs devops lowlevel
  csharp      = false; # configs webdev
  css         = false; # crypto
  cuda        = false; # css
  d           = false; # devops
  dart        = false; # devops
  diagnostics = false; # devops
  docker      = false; # devops
  elixir      = false; # devops
  elm         = false; # devops
  erlang      = false; # devops
  fennel      = false; # dotnet
  fish        = false; # full
  fortran     = false; # functional
  gitlab      = false; # functional universal
  gleam       = false; # gamedev
  glsl        = false; # gamedev lowlevel universal
  go          = false; # gamedev lowlevel universal
  godot       = false; # gamedev lowlevel universal
  haskell     = false; # gamedev scripting vim
  helm        = false; # general
  html        = false; # general notes
  java        = false; # gpu
  javascript  = false; # gpu
  json        = false; # gpu
  kotlin      = false; # jvm
  latex       = false; # jvm
  llvmIR      = false; # jvm universal
  lua         = false; # lisp
  markdown    = false; # lisp
  nginx       = false; # lowlevel
  nickel      = false; # lowlevel
  nix         = false; # lowlevel
  nushell     = false; # lowlevel
  objc        = false; # lowlevel
  odin        = false; # lowlevel
  perl        = false; # lowlevel
  powershell  = false; # notes
  protobuf    = false; # notes
  python      = false; # notes
  react       = false; # scripting
  ruby        = false; # scripting
  rust        = false; # scripting
  scala       = false; # scripting universal
  scheme      = false; # shells
  soldity     = false; # shells
  spelling    = false; # shells
  sql         = false; # shells
  svelte      = false; # universal
  swift       = false; # vim
  systemd     = false; # vim
  terraform   = false; # webdev
  toml        = false; # webdev
  typescript  = false; # webdev
  typst       = false; # webdev
  vim         = false; # webdev
  vue         = false; # webdev
  wasm        = false; # webdev
  wgsl        = false; # webdev
  yaml        = false; # webdev
  zig         = false; # webdev
}
